# 闪电链
## 2020，02-03~02-14
### 上线内容
开发一周测试一周，于2月13日上线
1. 离线消息微信通知
2. 补充缺少的应有的系统消息
4. 详情页点击返回键返回到对应的列表页
5. 优化用户体验

### 上线后后问题
1. 线上feign调用passport服务的接口出现连接被拒绝的异常。
异常信息：
2020-02-14 13:48:19.790 ERROR 13401 --- [nio-9019-exec-6] c.r.r.w.e.GlobalExceptionHandler         : http://10.10.164.126:9019/lightning-issue/5 请求异常
feign.RetryableException: Connection refused executing GET http://passport/passport/user/get/msg?userIds=1392&userIds=1115
        at feign.FeignException.errorExecuting(FeignException.java:132) ~[feign-core-10.2.3.jar!/:na]
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:113) ~[feign-core-10.2.3.jar!/:na]
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:78) ~[feign-core-10.2.3.jar!/:na]
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) ~[feign-core-10.2.3.jar!/:na]
        at com.sun.proxy.$Proxy187.getUserMsgByIds(Unknown Source) ~[na:na]
        at com.ruigu.rbox.workflow.service.impl.LightningIssueImpl.getIssueItem(LightningIssueImpl.java:566) ~[classes!/:0.0.1-SNAPSHOT]
重现方法：
手动调用超时接口/timeout/lightning
排查过程：
在项目根目录创建org.springframework.cloud.openfeign.ribbon，重写RetryableFeignLoadBalancer，打印调用服务的实际地址。
发布后重现错误，发现打印出的地址中有ip是127.0.0.1的，可以判断问题原因是passport服务注册的ip有问题。
随后把问题反馈给佳佳，才知道值passport的启动脚本有问题。
passport启动脚本修复后，重新发布passport，问题解决了。
根本原因：passport的启动脚本有问题
解决结果：已解决

2. 创建了库存临时调整申请后肖总的任务列表页面报错

根本原因：公共代码调整后，代码不兼容之前的流程配置和通知配置


记 4月30号 史诗级bug 望后来者谨记 （扣绩效的）
本次涉及到推推棒整个通知功能，导致后果自29号上线后至5月5号，所有通知丢失，大量问题无人受理，。
原因：正式环境配置文件没有修改。（在用类接收配置值时，一定要注意，不会报错）

记 7月20号 又见重大bug 不过这次并非是低级错误 而是由于推推棒数据日益增加导致的，
本次涉及到推推棒自动确认模块 由于早期批处理每次仅处理200条 并且将不能自动确认的问题一并查出，导致200条数据全都是不能自动确认的
